### ISSUE TITLE
Tag/capture the  extra reach

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#22]
**What feature would you like added?**
In the tag gamemode you can have extra reach to tag other people 
**How difficult do you think it would be to implement?**
IDK, kinda difficult

**Comment by RONAKPATELLLLLLL** [comment]
ok

**Comment by TheLazySquid** [comment]
> this feels like an impossible cheat to me, this kinda fits into the teleportation category
> 
> then again gimkit's security aint worth a jack

Yeah, just like with most interactions tagging is purely server side (which is why Gimkit gets janky with high ping)

**Comment by TheLazySquid** [comment]
I've managed to forcefully disable client-side collision, but the server sends out this packet which puts you back inbounds.
![image](https://user-images.githubusercontent.com/76746384/234981286-46eda856-3618-4421-8f3e-d8ec611dae01.png)
This does let you walk through thin walls, but there aren't many of those.

**Comment by CalebHacks** [comment]
Thats great

**Comment by CalebHacks** [comment]
That would be so cool

**Comment by TheLazySquid** [comment]
One practical application is being able to clip into and use these teleporters sometimes
![image](https://user-images.githubusercontent.com/76746384/234984967-5af34027-6ca3-458b-9859-a8fabb56ae26.png)
but the wall really does have to be very thin, such as these basketballs (you can't walk through them otherwise)
![image](https://user-images.githubusercontent.com/76746384/234985028-572a72de-3183-489d-b202-3b1689002e5b.png)

**Comment by PierceMichael** [comment]
> if you do disregard the packets, you just get desynced from the server and remain stationary for everyone else.

So could you maybe have the player desync with a keybind and move to where they want and resync?
