### ISSUE TITLE
For the new game mode 

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#36]
Mabye something that lets you insta win???

**Comment by TheLazySquid** [comment]
Hey! From the looks of it, there's not a lot unique to the new Gimkit platformer mode that can be done. I'll check if it's possible to do something like infinite double jump, but I think the odds aren't good.

**Comment by TheLazySquid** [comment]
Quick update: from the looks of it, there is a functional anticheat for the movement. If I manually set my jump height to be higher or gave myself more midair jumps, I would get snapped back to the correct position. Unless you can think of something else, it looks like this is a no-go.

**Comment by TheLazySquid** [comment]
The issue isn't jumping midair client-side, it's that the server detects that something is up and snaps you back to a valid position

**Comment by CalebHacks** [comment]
Something there nothing we can do?

**Comment by CalebHacks** [comment]
An idea is that sometimes the game lags a lot and I go through the ground and so does other people what if you could make a lag on purpose so you can make people fall.

**Comment by CalebHacks** [comment]
Maybe something that can record you movements then replay them?

**Comment by TheLazySquid** [comment]
Alright I've done some testing, here's what I've gotten so far:
The anticheat for movement is completely functional. Deleting collision from all the object causes rubberbanding, rather than clipping through them. I don't think that it's possible to do anything like fly or go through terrain. Turning up the player's speed or tweaking their gravity also results in the same rubberbanding.

The only option that looks possible to me would be what you said about replaying movements- how do you propose that that would be implemented? Like, it literally plays back the raw inputs, regardless of your position? I feel like you'd end up spending more time fiddling with starting/stopping/playing back recordings than just making the jumps yourself.
